version: '3'

services:
       postgre-server:
           image: 'praveen/postgre'
           container_name: 'postgre'
           expose: 
              - '5432'
       vertx-node:
              image: 'praveen/vertx'
              container_name: 'vertx' 
              ports:
                 - '4000:8080'
              links:
                 - 'postgre-server'
              environment:
                      - POSTGRE_HOST: postgre
                      - POSTGRE_PORT: 5432


                
