/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testproj;

import io.vertx.core.Vertx;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	 Vertx v =Vertx.vertx();
    	 ///HELLPE
    	 v.deployVerticle(new VertxHttpServer(3000));
    	 v.deployVerticle(new PostgresServer());
    	 while (true);
    }
}
